### ISSUE TITLE
Error with vite-plugin-gutenberg-block

### ISSUE THREAD

**Issue by eletitos** [evo-mark/vite-plugin-gutenberg-blocks#1]
hi!
I have tried vite-plugin-gutenberg-blocks and I have problems when I run "npm run dev" from the development folder. 
This is the error I get. 

![image](https://user-images.githubusercontent.com/36730057/226123764-eb698d12-18ec-4bd7-b6a2-827971c1134e.png)

 I hava tried several times, and I have also tried run the dev script from the block folder, but the error is always the same. 
 Any clue about what is going on?

Thanks in advance!

**Comment by craigrileyuk** [comment]
Seems to be an issue with the Windows file path separators. We’ll get a fix out for you shortly.

**Comment by craigrileyuk** [comment]
Just pushed v1.1.5, see if that's any better for you. I don't have a Windows machine to test on, but I think that should have got it.

**Comment by craigrileyuk** [comment]
No response in 2 weeks, so I'm assuming this was resolved for you.

**Comment by mindfullsilence** [comment]
One of my devs are coming across this error on v2.0.0
Possibly a regression?

**Comment by mindfullsilence** [comment]
Updating the `dist/plugins.js` file on line 8 to the following got us up and running for now:

```
const pwd = process.env.PWD || process.cwd();
```
