### ISSUE TITLE
Error when building a block with no CSS

### ISSUE THREAD

**Issue by frontycore** [evo-mark/vite-plugin-gutenberg-blocks#10]
First of all - thanks a lot for great plugin!

I found a little bug: when building a block with no `style` or `editorStyle` property in `block.json`, the build process fails in transform.js script (line 40 of dist version, line 56 is src version) with an error message:

*TypeError: Cannot read properties of undefined (reading 'replace')*

I tried to send a pull request, but it's are probably closed. The fix is easy though - use optional chaining:

```js
const stylesheets = [...style, editorStyle].flat(Infinity).map((s) => s?.replace("file:.", ""));
```

**Comment by craigrileyuk** [comment]
Fixed in version 2.x

Undefined stylesheets are now filtered out before processing.
