### ISSUE TITLE
Please push the latest changes the version seems old on github

### ISSUE THREAD

**Issue by anver** [evo-mark/vite-plugin-gutenberg-blocks#11]
Hi,
Please push the latest changes, the version seems different on npm and github.

**Comment by craigrileyuk** [comment]
Done. Good spot.

**Comment by anver** [comment]
I don't see any changes being pushed to github :)

**Comment by craigrileyuk** [comment]
There was a commit dated a few months back that had v2.2.0.

I've just pushed a few more updates for v2.3.0, but they need a bit more testing before release.
