### ISSUE TITLE
The emitted file "script.asset.php" overwrites a previously emitted file of the same name.

### ISSUE THREAD

**Issue by KBraNet** [evo-mark/vite-plugin-gutenberg-blocks#4]
When we have two files in different folder with the same name:
`"script": ["file:./script.js", "file:./front/script.js"]`
We have info after build:
`The emitted file "script.asset.php" overwrites a previously emitted file of the same name.
`

**Comment by craigrileyuk** [comment]
Closed with 1738691f6ecc77578f7058ff1268baa956ec2c8d and release v1.3.2
