### ISSUE TITLE
There are no output files for script and viewScript

### ISSUE THREAD

**Issue by KBraNet** [evo-mark/vite-plugin-gutenberg-blocks#5]
Build:
<img width="1053" alt="build-without-scripts" src="https://github.com/evo-mark/vite-plugin-gutenberg-blocks/assets/20502202/8c8694e9-20f0-4307-a66c-3dbe101f71c8">
Should be that:
<img width="1609" alt="buildwithscripts" src="https://github.com/evo-mark/vite-plugin-gutenberg-blocks/assets/20502202/04672570-5b56-414b-93ce-fbe56df5348d">

**Comment by KBraNet** [comment]
PR: https://github.com/evo-mark/vite-plugin-gutenberg-blocks/pull/6

**Comment by craigrileyuk** [comment]
Frontend scripts are not part of the main build and there's too much hackery involved to make them so.

Using esbuild to sideload and emit these as ancillary assets is the way we've chosen to support this feature.
