### ISSUE TITLE
Build does not track files imported into script and viewScript

### ISSUE THREAD

**Issue by KBraNet** [evo-mark/vite-plugin-gutenberg-blocks#7]
I hope you're not tired of me :)
When we split the script into several files, changes to the imported files do not trigger the scripts to be rebuilt with the --watch flag.
Example:
```
// script.js
import Accordion from './front/Accordion.js';

document.addEventListener('DOMContentLoaded', (_event) => {
    const containerSelector = '.js-accordion .frontkom-accordion__button';
    const accordion = new Accordion(
        document.querySelectorAll(containerSelector),
    );
    accordion.init();
});
```
When we change something in Accordion.js, vite does not track these changes and we need go to script.js and re save this file to reload build

I don't want to force my changes but in this configuration everything works fine :) #6 
https://github.com/evo-mark/vite-plugin-gutenberg-blocks/pull/6/commits/3e0546d42e229ea4efaf365592afa3ae66cafffb#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012

**Comment by craigrileyuk** [comment]
Fixed in Version 2.1
