### ISSUE TITLE
Error when npx create and prompt

### ISSUE THREAD

**Issue by khsuzan** [evo-mark/vite-plugin-gutenberg-blocks#9]
There is an issues in create.mjs file. 
The issue is whenever prompted to write an npm package name, after inputting any name even just 'example' it showing that npm package only can contain small, numbers and hypens, but litterally in create.mjs file after receiving the prompt value its appending @ and / as suffix prefix, so everytime it makes an error.

**Comment by anver** [comment]
leaving empty value for the npm package fixed it for me

![image](https://github.com/evo-mark/vite-plugin-gutenberg-blocks/assets/506491/59c8329b-51ad-4f3f-b1c5-0db8b70b0382)

**Comment by craigrileyuk** [comment]
I'll add a note on the first question for "(leave empty for none)" although this won't affect existing development environments that have been created.

**Comment by craigrileyuk** [comment]
Just seen that I read the issue incorrectly.

You are correct, the prefix and suffix were being added and thus causing the validation to fail. This has been fixed in the latest version.
